#!/usr/bin/env python3
"""Regenerate each project's MEMORY.md from the frontmatter of its memory files.

    ./scripts/gen-memory-index.py            # rewrite every index under memory/
    ./scripts/gen-memory-index.py --check    # exit 1 if any index is stale, write nothing

MEMORY.md is the file Claude Code loads into context at session start: one line per
memory, name plus hook. Hand-maintaining it has two costs this removes.

1. It drifts. Nothing enforces that a line exists for every file, or that a line does
   not outlive the file it points at.
2. It is the ONLY part of file memory that two machines reliably conflict on. The
   memory files themselves are separate and small, so git merges them cleanly; the
   index is a single append-only list both sides add to, so concurrent sessions
   collide on nearly every sync. A generated file is derived, and derived files are
   regenerated rather than merged.

Order is alphabetical by `name` — deterministic and machine-independent, so the same
inputs give byte-identical output on both machines. (Insertion order would have been
nicer to read but cannot be reproduced from the files alone.)
"""
import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Memory lives in its own private repo, so the root is resolved at run time:
# an explicit path argument wins, then $CLAUDE_MEMORY_REPO, then the default clone.
def memory_root() -> Path:
    for arg in sys.argv[1:]:
        if not arg.startswith("-"):
            return Path(arg).expanduser().resolve()
    env = os.environ.get("CLAUDE_MEMORY_REPO")
    if env:
        return Path(env).expanduser().resolve()
    return Path.home() / "devbox" / "source" / "dotfiles-claude-memory"
HEADER = (
    "# Memory Index\n"
    "\n"
    "<!-- Generated by scripts/gen-memory-index.py from each file's frontmatter.\n"
    "     Do not hand-edit: edit the memory file's `description:` instead. -->\n"
    "\n"
)


def read_frontmatter(path):
    """Return (name, description) from a memory file, or None if it has no frontmatter."""
    text = path.read_text(encoding="utf-8", errors="replace")
    match = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not match:
        return None
    block = match.group(1)
    fields = {}
    for key in ("name", "description"):
        found = re.search(rf"^{key}:\s*(.+?)\s*$", block, re.M)
        if found:
            fields[key] = found.group(1).strip().strip('"').strip("'")
    if "name" not in fields:
        return None
    return fields["name"], fields.get("description", "")


def build_index(memory_dir):
    rows = []
    problems = []
    for path in sorted(memory_dir.glob("*.md")):
        if path.name == "MEMORY.md":
            continue
        parsed = read_frontmatter(path)
        if parsed is None:
            problems.append(f"{path.name}: no frontmatter `name:`, skipped")
            continue
        name, description = parsed
        rows.append((name, path.name, description))
    rows.sort(key=lambda row: row[0].lower())
    lines = [HEADER]
    for name, filename, description in rows:
        title = name.replace("-", " ")
        title = title[:1].upper() + title[1:]
        lines.append(f"- [{title}]({filename})" + (f" — {description}\n" if description else "\n"))
    return "".join(lines), problems, len(rows)


def main():
    check = "--check" in sys.argv[1:]
    stale = []
    root = memory_root()
    if not root.is_dir():
        print(f"no memory repo at {root} — nothing to index (it is optional).")
        return 0
    for memory_dir in sorted(root.iterdir()):
        # The memory repo root holds label directories directly, so .git (and any
        # other dotfile) sits beside them and must never be indexed as one.
        if not memory_dir.is_dir() or memory_dir.name.startswith("."):
            continue
        content, problems, count = build_index(memory_dir)
        index_path = memory_dir / "MEMORY.md"
        current = index_path.read_text(encoding="utf-8") if index_path.exists() else None
        changed = current != content
        for problem in problems:
            print(f"  !! {memory_dir.name}/{problem}", file=sys.stderr)
        if check:
            if changed:
                stale.append(memory_dir.name)
            continue
        if changed:
            index_path.write_text(content, encoding="utf-8")
            print(f"  wrote {memory_dir.name}/MEMORY.md ({count} entries)")
    if check and stale:
        print("stale index: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
